### PR TITLE
Fix minor errors (sendAsyncMessage / unknown property 'appearance')

### PR DESCRIPTION
**Pull request by Rikk**
Description at commits...

### CODE REVIEW

**Comment by piroor** [comment]
The commit https://github.com/Rikk/multipletab/commit/10902044915969098360c1d19ccd105b294dc3a8 seems unnecessary. Because CSS properties starting with vendor prefix like `-moz-appearance` are experimental implementation for future CSS spec and it will be unprefixed after the spec become public recommendation spec, we should put both versions: prefixed and unprefixed.

**Comment by piroor** [comment]
I close this PR, but thanks a lot!

**Comment by Rikk** [comment]
As noted in commit description, that unprefixed property is not supported and triggers error in console.

**Comment by piroor** [comment]
Hmm,

**Comment by piroor** [comment]
Hmm, I didn't know that `appearance` is removed from latest plan of the CSS spec.
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance
So as you told, `-moz-appearance` never been renamed to the unprefixed version. My "safety net" policy is just to prepare for the renaming in the future. Because `-moz-appearance` never been unprefixed, I agree to remove unprefixed version `appearance` from the CSS file.

**Comment by Rikk** [comment]
Thanks @piroor
I'm glad you give attention to MTH! :satisfied:

**Pull request merged**
